Use the following code for the questions below:

In [1]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [2]:
print(a[a < 0])
print(len(a[a < 0]))

[-2 -1 -6 -7]
4


2. How many positive numbers are there?

In [3]:
print(a[a > 0])
print(len(a[a > 0]))

[ 4 10 12 23  3]
5


3. How many even positive numbers are there?

In [4]:
print(a[(a > 0) & (a % 2 == 0)])
print(len(a[a > 0]))

[ 4 10 12]
5


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [5]:
a_plus_3 = a + 3
print(a_plus_3)
print(a_plus_3[a_plus_3 > 0])
print(len(a_plus_3[a_plus_3 > 0]))

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]
[ 7 13 15 26  1  2  3  3  3  6]
10


5. If you squared each number, what would the new mean and standard deviation be?

In [6]:
a_sqrd = a ** 2
print(a_sqrd)
print(f'mean: {a_sqrd.mean()}')
print(f'std dev: {a_sqrd.std()}')

[ 16 100 144 529   4   1   0   0   0  36   9  49]
mean: 74.0
std dev: 144.0243035046516


6. A common statistical operation on a dataset is **centering**. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this [link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering.

In [7]:
a_centered = a - a.mean()
print(a.mean())
print(a_centered)

3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


7. Calculate the z-score for each data point. Recall that the z-score is given by:

$$ Z = \frac{x − μ}{σ} $$


In [8]:
a_z_scores = (a - a.mean())/ (a.std())
a_z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from [More Numpy Practice](https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your numpy_exercises.py and add your solutions.

In [9]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use python's built in functionality/operators to determine the following:

In [80]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of
# all the numbers in above list
sum(a)

55

In [81]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum
# of all the numbers in the above list
min(a)

1

In [82]:
# Exercise 3 - Make a variable named max_of_a to hold the max number
# of all the numbers in the above list
max(a)

10

In [83]:
# Exercise 4 - Make a variable named mean_of_a to hold the average
# of all the numbers in the above list
sum(a) / len(a)

5.5

In [87]:
# Exercise 5 - Make a variable named product_of_a to hold the
# product of multiplying all the numbers in the above list together
product_of_a = 1
for num in a:
    product_of_a *= number
product_of_a

1073741824

In [90]:
# Exercise 6 - Make a variable named squares_of_a. 
# It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for num in a:
    squares_of_a.append(num**2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [93]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for num in a:
    if(num % 2 != 0):
        odds_in_a.append(num)
odds_in_a

[1, 3, 5, 7, 9]

In [96]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for num in a:
    if(num % 2 == 0):
        evens_in_a.append(num)
evens_in_a

[2, 4, 6, 8, 10]

In [13]:
# What about life in two dimensions? A list of lists is
# matrix, a table, a spreadsheet, a chessboard...
# Setup 2: Consider what it would take to find the sum, min, max,
# average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b_arr = np.array(b)
b_arr

array([[3, 4, 5],
       [6, 7, 8]])

In [14]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [15]:
b_arr.sum()

33

In [16]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [17]:
b_arr.min()

3

In [18]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [19]:
b_arr.max()

8

In [20]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [21]:
b_arr.mean()

5.5

In [25]:
# Exercise 5 - refactor the following to use numpy for calculating
# the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [24]:
b_arr.prod()

20160

In [26]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [28]:
b_arr ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [29]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [34]:
b_arr[b_arr % 2 == 1]

array([3, 5, 7])

In [35]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [36]:
b_arr[b_arr % 2 == 0]

array([4, 6, 8])

In [37]:
# Exercise 9 - print out the shape of the array b.
b_arr.shape

(2, 3)

In [38]:
# Exercise 10 - transpose the array b.
b_arr.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [40]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b_arr.reshape((1, 6))

array([[3, 4, 5, 6, 7, 8]])

In [41]:
# Exercise 12 - reshape the array b to be a list of 6 lists,
# each containing only 1 number (6 x 1)
b_arr.reshape((6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [42]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy
# array prior to using numpy array methods.
c_arr = np.array(c)
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [46]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(f"""
       min: {c_arr.min()} \t sum: {c_arr.sum()}
       max: {c_arr.max()} \t product: {c_arr.prod()}
        """)


       min: 1 	 sum: 45
       max: 9 	 product: 362880
        


In [48]:
# Exercise 2 - Determine the standard deviation of c.
c_arr.std()

2.581988897471611

In [49]:
# Exercise 3 - Determine the variance of c.
c_arr.var()

6.666666666666667

In [50]:
# Exercise 4 - Print out the shape of the array c
c_arr.shape

(3, 3)

In [51]:
# Exercise 5 - Transpose c and print out transposed result.
c_arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
# Exercise 6 - Get the dot product of the array c with c. 
c_arr.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [57]:
# Exercise 7 - Write the code necessary to sum up the result of
# c times c transposed. Answer should be 261
(c_arr * c_arr.T).sum()

261

In [58]:
# Exercise 8 - Write the code necessary to determine the product of
# c times c transposed. Answer should be 131681894400.
(c_arr * c_arr.T).prod()

131681894400

In [59]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d_arr = np.array(d)
d_arr

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [61]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d_arr)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [66]:
np.set_printoptions(suppress=True)
np.sin(d_arr * (np.pi / 180) )

array([[ 1.        ,  0.5       ,  0.70710678,  0.        ,  0.8660254 ,
         0.        ],
       [ 0.70710678, -1.        , -0.5       , -1.        ,  1.        ,
         0.        ],
       [ 0.8660254 ,  0.70710678, -0.70710678,  1.        , -0.70710678,
         0.        ]])

In [67]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d_arr * (np.pi / 180) )

array([[ 0.        ,  0.8660254 ,  0.70710678,  1.        , -0.5       ,
        -1.        ],
       [ 0.70710678,  0.        ,  0.8660254 , -0.        ,  0.        ,
         1.        ],
       [ 0.5       ,  0.70710678,  0.70710678,  0.        ,  0.70710678,
        -1.        ]])

In [70]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d_arr * (np.pi / 180) )

array([[ 1.63312394e+16,  5.77350269e-01,  1.00000000e+00,
         0.00000000e+00, -1.73205081e+00, -1.22464680e-16],
       [ 1.00000000e+00, -1.63312394e+16, -5.77350269e-01,
         5.44374645e+15,  1.63312394e+16,  0.00000000e+00],
       [ 1.73205081e+00,  1.00000000e+00, -1.00000000e+00,
         1.63312394e+16, -1.00000000e+00, -1.22464680e-16]])

In [71]:
# Exercise 4 - Find all the negative numbers in d
d_arr[d_arr < 0]

array([-90, -30, -45, -45])

In [72]:
# Exercise 5 - Find all the positive numbers in d
d_arr[d_arr > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [75]:
# Exercise 6 - Return an array of only the unique numbers in d
np.unique(d_arr)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [76]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d_arr))

11

In [77]:
# Exercise 8 - Print out the shape of d.
d_arr.shape

(3, 6)

In [78]:
# Exercise 9 - Transpose and then print out the shape of d.
d_arr.T.shape

(6, 3)

In [79]:
# Exercise 10 - Reshape d into an array of 9 x 2
d_arr.reshape((9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

**Bonus** 

From: https://github.com/rougier/numpy-100

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [29]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print()

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)


#### 12. Create a 3x3x3 array with random values (★☆☆)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


#### 22. Normalize a 5x5 random matrix (★☆☆)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)


#### 30. How to find common values between two arrays? (★☆☆)


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


#### 40. Create a random vector of size 10 and sort it (★★☆)


#### 41. How to sum a small array faster than np.sum? (★★☆)


#### 42. Consider two random array A and B, check if they are equal (★★☆)


#### 43. Make an array immutable (read-only) (★★☆)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


#### 49. How to print all the values of an array? (★★☆)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)


#### 57. How to randomly place p elements in a 2D array? (★★☆)


#### 58. Subtract the mean of each row of a matrix (★★☆)


#### 59. How to sort an array by the nth column? (★★☆)


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


#### 63. Create an array class that has a name attribute (★★☆)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


#### 69. How to get the diagonal of a dot product? (★★★)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


#### 72. How to swap two rows of an array? (★★★)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


#### 75. How to compute averages using a sliding window over an array? (★★★)


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)